### ISSUE TITLE
Phi2 optimization

### ISSUE THREAD

**Issue by KL0nLutiy** [fancyIX/sgminer-phi2-branch#100]
Hello, @fancyIX, I saw you add new echo-f kernel you can use it for phi2 too if it faster.

**Comment by fancyIX** [comment]
@KL0nLutiy Yeah, it should be faster a little bit. The dominate factor is lyra2 so I don't expect much. Will do anyway.

**Comment by fancyIX** [comment]
Won't fix because IP theft is happening (not to this miner though) in some closed source miner. It’s a huge effort to write GCN asm code and build optimized bin kernels including GCN code. If someone can just use your bin files in closed source miner without giving you any credit, what is the point of those effect building those bin kernels...
