### ISSUE TITLE
Reduce power consumption

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#64]

**Comment by lordgamegenie** [comment]
Is there a way to increase power consumption?  I want to go opposite because it appears this miner is barely working my RX 550 .  It's only at 66 degrees Celsius and 19% fan speed.   
I'm only getting 122.0K from the status at the top.   I was getting 2.62M when I was mining with one of my VEGA 56, even that way too low.  
I switched my VEGAs to Ethereum and they are drawing 15M a piece.  I know the algorithms are different but why is lyzra2z not fully utilizing GPU power. It makes mining painfully slow.

**Comment by fancyIX** [comment]
@lordgamegenie Your speed for lyra2z is normal with this miner. Teamredminer is much faster than this miner. Maybe you'd like to try that.
