### ISSUE TITLE
Dual mining

### ISSUE THREAD

**Issue by KL0nLutiy** [fancyIX/sgminer-phi2-branch#71]
Hello, @fancyIX, what about the dual mining? For example, ethash + lyra2z or ethash + phi2, even if your implementation of lyra2 is not the fastest, dual mining will be a good reason to use your miner. There is a good opensource implementation of Ethash : https://github.com/ethereum-mining/ethminer/tree/master/libethash-cl/kernels/isa. An example of dual mining kernel: https://github.com/zawawawa/GatelessGateSharp/blob/v1.3/GatelessGateSharp/Kernels/ethash_pascal.cl

**Comment by fancyIX** [comment]
Won't fix because IP theft is happening (not to this miner though) in some closed source miner. It’s a huge effort to write GCN asm code and build optimized bin kernels including GCN code. If someone can just use your bin files in closed source miner without giving you any credit, what is the point of those effect building those bin kernels...
